details/urls.py
from django.urls import path
from .views import HomePage, Qualifications 
from django.conf.urls.static import static
from django.conf import settings

app_name = 'details'

urlpatterns = [
    path('', HomePage.as_view(), name="index"),
    path('about/', Qualifications.as_view(), name="about")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 
from details import urls as details_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(details_urls, namespace='feed'))
]

details/models.py
from django.db import models
from sorl.thumbnail import ImageField
# Create your models here.
class Styles(models.Model):
    description = models.CharField(max_length=255)
    image = ImageField()
    profile_image = ImageField()
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Skills(models.Model):
    image = ImageField()
    title = models.CharField(blank=True,max_length=100)
    description = models.CharField(max_length=255)
    text_field = models.CharField(max_length=1500 ,blank=True)
    
    def __str__(self):
        
        return self.title
    
class Education(models.Model):
    organisation = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    certificate = ImageField()
    def __str__(self):
        return self.organisation
class EduStyles(models.Model):
    title = models.CharField(max_length=100)
    image = ImageField();
    def __str__(self):
       return self.title 
   
class About(models.Model):
    name= models.CharField(max_length=100);
    about= models.CharField(max_length=255);
    
    def __str__(self):
        return self.name

details/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from .models import Styles, Skills, Education, EduStyles
from django.views.generic.detail import DetailView

# Create your views here.
class HomePage(TemplateView):
    template_name = "details/home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['styles'] = Styles.objects.all()
        context['skills'] = Skills.objects.all()
        return context
    
    
class Qualifications(ListView):
    model = Education
    template_name = 'details/education.html'
    context_object_name = 'educations'
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        educations = self.get_queryset();
        
        enumerated_educations = list(enumerate(educations, start=1))
        odd_educations = [edu for index, edu in enumerated_educations if index % 2 == 1]
        even_educations = [edu for index, edu in enumerated_educations if index % 2 == 0]
        context['pairs'] = zip(odd_educations, even_educations)
        context['eduStyles'] = EduStyles.objects.all()
        return context
    

details/templates/details/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


{% endblock %}

details/templates/details/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
 <link rel="stylesheet" href="{% static 'details/style.css' %}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_css %}

    {% endblock %}
</head>

<body>


  {% block content %}
{% include 'nav.html' %}
  {% endblock %}
  <!-- {% include 'details/footer.html' %} -->
  <script>
  // Get the elements
  document.addEventListener("DOMContentLoaded", () => {
  // Select all popup triggers and popups
  const popupTriggers = document.querySelectorAll(".popupTrigger");
  const popups = document.querySelectorAll(".popup");

  // Iterate through popup triggers and attach event listeners
  popupTriggers.forEach((trigger, index) => {
    const popup = popups[index]; // Match the popup to the trigger
    const closeButton = popup.querySelector(".close-button");

    // Show the popup
    trigger.addEventListener("click", () => {
      popup.style.display = "flex";
    });

    // Hide the popup
    closeButton.addEventListener("click", () => {
      popup.style.display = "none";
    });

    // Hide the popup when clicking outside the content
    popup.addEventListener("click", (e) => {
      if (e.target === popup) {
        popup.style.display = "none";
      }
    });
  });
});
  const links = document.querySelectorAll('.nav-links li');
  const indicator = document.querySelector('.indicator');
  const navbar = document.querySelector('.navbar');

  links.forEach((link) => {
    link.addEventListener('mouseover', (e) => {
      const { left, width } = link.getBoundingClientRect();
      const navbarLeft = navbar.getBoundingClientRect().left;

      indicator.style.width = `${width}px`;
      indicator.style.left = `${left - navbarLeft}px`;
    });

    link.addEventListener('mouseout', () => {
      indicator.style.width = '0';
    });
  });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

details/templates/details/columns.html
<div class="container text-center">
    <div class="row justify-content-start">
      <div class="col-4">
        One of two columns
      </div>
      <div class="col-4">
        One of two columns
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-4">
        One of two columns
      </div>
      <div class="col-4">
        One of two columns
      </div>
    </div>
    <div class="row justify-content-end">
      <div class="col-4">
        One of two columns
      </div>
      <div class="col-4">
        One of two columns
      </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-4">
          One of two columns
        </div>
        <div class="col-4">
          One of two columns
        </div>
      </div>
      <div class="row justify-content-start">
        <div class="col-4">
          One of two columns
        </div>
        <div class="col-4">
          One of two columns
        </div>
      </div>
    </div>
  </div>

details/templates/details/education.html
{% extends 'details/base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'details/style.css' %}">
{% endblock %}
{% block content %}
{% for style in eduStyles %}
<div class="container-1">
  <div class="content-card shadow"
    style="color:black;background-image: url('{{style.image.url}}');background-size:cover;">
    {% endfor %}
    {% include 'nav.html' %}
    <div class="container-fluid text-center">

      {% for odd, even in pairs %}
      <div id="popup" class="popup rounded-4"">
    <div class=" popup-content" style="border:2px solid #fff;">
        <span class="close-button"></span>
        <img src="{{ odd.certificate.url }}" class="popup-image"
          style="width:100%; height:150px;">
      </div>
    </div>
    <div id="popup" class="popup rounded-4"">
      <div class=" popup-content" style="border:2px solid #fff;">
          <span class="close-button"></span>
          <img src="{{ even.certificate.url }}" class="popup-image"
            style="width:100%; height:150px;">
        </div>
      </div>


    <div class="row rounded cards2" id="cards" style="text-align: center; margin:auto; justify-content:center; ">
      <div class="col-1 col-md-1 col-lg-1 rounded-4 p-0 mx-3 shadow popupTrigger clickable-image3"
        style="border:1px solid #fff; background:rgba(0,0,0,0.8);height:170px ;">
        <div id="list-example" class="d-flex flex-column gap-2 simple-list-group-scrollspytext-center"
          style="padding-top:30px; color:#fff">
          <a class=" rounded my-4"  href="#simple-list-item-1" style="color:#fff">{{odd.organisation}}</a>
        </div>
      </div>

      <div class="col-7 col-sm-7 col-md-8 col-lg-9 rounded-4 shadow "
        style="border:1px solid #fff; height:170px; overflow:auto; color:#fff; background:rgba(0,0,0,0.8)">
        <div data-bs-spy="scroll" data-bs-target="#simple-list-example" data-bs-offset="0" data-bs-smooth-scroll="true"
          class="scrollspy-example" tabindex="0">
          <h4 id="simple-list-item-1" style="color:#fff">{{ odd.organisation}}</h4>
          <p class="my-3"> {{ odd.description}} </p>
        </div>
      </div>
      </div>


      <div class="row rounded cards2 my-4 pt-4" id="cards" style="text-align: center; margin:auto; justify-content:center">
      <div class="col-7 col-sm-7 col-md-8 col-lg-9 rounded-4 mx-3 shadow "
      style="border:1px solid #fff; height:170px; overflow:auto; color:#fff; background:rgba(0,0,0,0.8)">
      <div data-bs-spy="scroll" data-bs-target="#simple-list-example" data-bs-offset="0" data-bs-smooth-scroll="true"
        class="scrollspy-example" tabindex="0">
        <h4 id="simple-list-item-1" style="color:#fff">{{ even.organisation}}</h4>
        <p class="my-3"> {{ even.description}} </p>
      </div>
    </div>
    <div class="col-1 col-md-1 col-lg-1 rounded-4 p-0 shadow popupTrigger clickable-image3"
    style="border:1px solid #fff; background:rgba(0,0,0,0.8);height:170px ;">
    <div id="list-example" class="d-flex flex-column gap-2 simple-list-group-scrollspy text-center"
      style="padding-top:30px; color:#fff">
      <a class=" rounded my-4" href="#simple-list-item-1" style="color:#fff">{{even.organisation}}</a>
    </div>
  </div>
    </div>
    </div>

    <br>
    {% endfor %}


    {% include 'details/footer.html'%}
  </div>
</div>
</div>
{% block extra_content %}
{% endblock %}
{% endblock %}

details/templates/details/footer.html
<footer style="background: rgba(0, 0, 0, 1) ; color: white; padding: 0; margin:0 ;text-align: center; border-radius:15px; width: 100%;">
    <br>
    <div>
      <p>&copy; 2024 Christian. All Rights Reserved.</p>
    </div>
    <div>
      <p>Connect with me on 
        <a href="https://www.linkedin.com/in/your-profile" target="_blank" style="color: #1DA1F2;">LinkedIn</a> | 
        <a href="https://github.com/your-profile" target="_blank" style="color: #1DA1F2; padding:5px;">GitHub</a>
      </p>
    </div>
    <br>
  </footer>

details/templates/details/home.html
{% extends 'details/base.html' %}
{% load static %}
{% block content %}
<div class="container-1">
<div class="content-card shadow">
{% for style in styles %}
<div class="container-fluid text-center ps-0 pe-0 d-wrap shadow-lg image-container" style="background-image: 
     linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)),
      url('{{style.image.url}}');">
{% include 'nav.html' %}
    <div class=" row pl-0" style="height: 450px; width:100%">
        <div class="col-4 content1">
            <h2 class="intro">{{ style.description}}</h2>
        </div>
        <div class="col d-md-block ">
            <div class="content">
            </div>
        </div>
        <div class="col-6 col-md-5 col-lg-5 col-xl-4 ">
        <a href="{% url 'details:about' %}"><div class="content clickable-image2" 
        style="background-image:
        url('{{style.profile_image.url}}');"> 
        </div></a>
        </div>
    </div>
</div>
{% endfor %}

<div class="d-flex flex-row justify-content-around">
    <div class="p-2" style="border-bottom:3px solid black">
        <h3>Skills I am proficient in</h3>
    </div>
</div>

<div class="row flex-wrap text-center m-0">
    {% for skill in skills %}
    <div id="popup" class="popup rounded-4">
        <div class="popup-content">
            <span class="close-button"></span>
            <h2>{{skill.title }}</h2>
            <hr>
            <p>{{ skill.text_field}}</p>
        </div>
    </div>
    <div class="col-6 col-md-6 col-lg-3 d-flex card-popup">
        <div class="col rounded-4 p-0  shadow-lg my-2   "" style=" height:400px; width:100%;">
            <div class="color popupTrigger clickable-image" style="background-image: url('{{ skill.image.url }}');">
            </div>
            <div class="write">
                <h5>{{skill.title}}</h5>
                <div class="writeNest d-flex">
                </div>
                <div class="person d-flex border-top border-2  rounded-2">
                    <p class="peoplep">{{ skill.description}} </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% block extra_content %}
    {% endblock %}
</div>


{% include 'footer.html' %}
</div>
</div>
{% endblock %}

details/templates/details/nav.html
<nav class="navbar">
    <div class="logo">CHRISTIAN MEINTJES</div>
    <ul class="nav-links">
      <li><a href="/">HOME</a></li>
      <li><a href="{% url 'details:about' %}">EDUCATION</a></li>
    </ul>
    <div class="indicator"></div>
  </nav>